// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT3H1KSgfqXV6RDyb-S5dNWyM1YHLVGy4',
    appId: '1:1034297631164:web:84ec6c334ca03901ea4bb9',
    messagingSenderId: '1034297631164',
    projectId: 'app2-7546d',
    authDomain: 'app2-7546d.firebaseapp.com',
    storageBucket: 'app2-7546d.firebasestorage.app',
    measurementId: 'G-9ZXHKR6496',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoynzcFLub-SKtOkzFG3QeZyK_mJI1Nb4',
    appId: '1:1034297631164:android:1ecb6cfb0cdbaad6ea4bb9',
    messagingSenderId: '1034297631164',
    projectId: 'app2-7546d',
    storageBucket: 'app2-7546d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXMHul-UlBez1cC8aiiF_cjHyNeEvQMFM',
    appId: '1:1034297631164:ios:94f6e05564381255ea4bb9',
    messagingSenderId: '1034297631164',
    projectId: 'app2-7546d',
    storageBucket: 'app2-7546d.firebasestorage.app',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXMHul-UlBez1cC8aiiF_cjHyNeEvQMFM',
    appId: '1:1034297631164:ios:94f6e05564381255ea4bb9',
    messagingSenderId: '1034297631164',
    projectId: 'app2-7546d',
    storageBucket: 'app2-7546d.firebasestorage.app',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT3H1KSgfqXV6RDyb-S5dNWyM1YHLVGy4',
    appId: '1:1034297631164:web:a0fc811582ff5f7eea4bb9',
    messagingSenderId: '1034297631164',
    projectId: 'app2-7546d',
    authDomain: 'app2-7546d.firebaseapp.com',
    storageBucket: 'app2-7546d.firebasestorage.app',
    measurementId: 'G-NL6C46NLH5',
  );

}